### ISSUE TITLE
fitsblender is using removed fits calls

### ISSUE THREAD

**Issue by nden** [spacetelescope/fitsblender#3]
The `fits.new_table()` calls need to be replaced by current current `astropy.io.fits` calls.
This is causing errors in the drizzlepac regression tests.

**Comment by jhunkeler** [comment]
Linking to #4

**Comment by mcara** [comment]
I am working on replacing ``new_table()`` calls in other packages. While I was working on this I have noticed that @jhunkeler already replaced these calls in commit https://github.com/spacetelescope/fitsblender/commit/5b0b32ab6f29510dca9a19dfdd9136a885600bd5 Unfortunately it appears that @jhunkeler 's fix is no correct: when ``tbtype`` is not specified then the default is ``BinTableHDU`` and not ``TableHDU``. In PR https://github.com/spacetelescope/fitsblender/pull/6 I fix this issue.

CC @stsci-hack

**Comment by jhunkeler** [comment]
@mcara Ack, sorry about that

**Comment by larrybradley** [comment]
Fixed in #6.
